// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcaavtbbhzhjrgqnubzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjYWF2dGJiaHpoanJncW51YnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTAwNjksImV4cCI6MjA2NTEyNjA2OX0.gnJ5niSBKWK2yFZfAgHeuOK-lf9iPHMyT3VvG8p6mlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);